### ISSUE TITLE
Can't compile cuda samples

### ISSUE THREAD

**Issue by magistri** [NVIDIA/cuda-samples#22]
Hi there 

I have troubles compiling the cuda samples in version 10.2 on a fresh ubuntu 18.04.
here's the issue:

`In file included from cudaNvSci.cpp:12:0:
cudaNvSci.h:14:10: fatal error: nvscibuf.h: No such file or directory
 #include <nvscibuf.h>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:394: recipe for target 'cudaNvSci.o' failed
make[1]: *** [cudaNvSci.o] Error 1
make[1]: Leaving directory '/home/federico/NVIDIA_CUDA-10.2_Samples/0_Simple/cudaNvSci'
Makefile:51: recipe for target '0_Simple/cudaNvSci/Makefile.ph_build' failed
make: *** [0_Simple/cudaNvSci/Makefile.ph_build] Error 2` 

any idea?

**Comment by Helenll** [comment]
Same problem! cannot find this .h file

**Comment by Evanslooten** [comment]
I am also experiencing this issue on a fresh ubuntu 18.04 install. Using Nvidia-drivers-440 from apt and installing with the run file.

**Comment by Helenll** [comment]
it seems the default installation just dose not include nvscibuf.h, while the sample needs it?

**Comment by Naowak** [comment]
Hello, I encountered the same problem. It seems that you can continue the build with
`make -k`.

**Comment by mdoijade** [comment]
@magistri  @Helenll @Evanslooten  you can continue the build with `make -k` while using master Makefile this will allow make to skip this error due to build failure of cudaNvSci sample. 

As documented in the CUDA 10.2 release notes, the NvSci interop support is a new BETA feature to CUDA 10.2 and hence it's broad support is limited at this current time.  The cudaNvSci sample that is contained in the CUDA 10.2 toolkit requires a new NvStreams development package that has, to date, not yet been released.  NvStreams is a product of NVIDIA Automotive SW and is already supported in DRIVE OS aarch64 Linux on [DRIVE OS 5.1.12.0](https://docs.nvidia.com/drive/drive_os_5.1.12.0L/nvvib_docs/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide%2FGraphics%2Fnvsci.html%23) . The x86_64 support package for Nvstreams is new and is due to be released in late January of 2020 as a part of the DRIVE OS 5.1.12.4 release.  If you are interested to obtain the upcoming release of Nvstreams support for DRIVE OS on x86_64 please register for an account at https://developer.nvidia.com/DRIVE-AGX-program The initial release of the BETA Nvstreams x86_64 library package will be handled via https://partners.nvidia.com/  which is a credentialed access portal automotive partners for obtaining all related DRIVE OS software.

**Comment by kamrankausar** [comment]
make: Target 'all' not remade because of errors.

**Comment by twobob** [comment]
>  The initial release of the BETA Nvstreams x86_64 library package will at blah blah and you don't have it

Then don't shove/require/embed it in the basic build samples? duh.

**Comment by Vfitstory** [comment]
I specifically logged in to second twobob.

**Comment by qhaas** [comment]
Seeing the following 'not founds' in EL8, CUDA 11 samples, CUDA 11 SDK + cudnn8, and proprietary driver 450.51.05, which is [oddly a beta driver in the stable repo](https://forums.developer.nvidia.com/t/beta-driver-is-the-default-in-rhel-8/140973):
```
$ make -j$(nproc) 2>&1 | sort -u | grep -i 'not found'
>>> WARNING - libnvscibuf.so not found, please install libnvscibuf.so <<<
>>> WARNING - libnvscisync.so not found, please install libnvscisync.so <<<
>>> WARNING - nvscibuf.h not found, please install nvscibuf.h <<<
>>> WARNING - nvscisync.h not found, please install nvscisync.h <<<
```

`yum provides` and `locate` do not return results for said files.

**Comment by twobob** [comment]
Can't understand why this issue was closed tbh

**Comment by sentientmachine** [comment]
I got the same error and found a fix.  You did a google search for a driver and you used an older version: Make sure you've got the most up to date one.

I'm running Gentoo Linux x86_64, PC with dual (two) Geforce RTX 2080Ti using `root> sh NVIDIA-Linux-x86_64-418.43.run`

    make: Target ' not remade because of errors.

I downloaded a month old version of the driver.  I went to `nvidia.com`, go to 'geforce drivers` choose your exact GPU make/model, select `x86_64 Bit` ask for the latest one, and whisks you to a new page with: **NVIDIA-Linux-x86_64-455.45.01.run** note the version upgrade to: `455.45.01` Download that and run, and and the installer reports a success.

**Comment by sephethus** [comment]
Every single answer with Linux has a new problem. Installing the latest 455.45 drivers lead to an error that an X server is running. Now I have to solve that problem. Will it ever end?

**Comment by sentientmachine** [comment]
@sephethus 
About the error of an X server is running.  I got a similar sounding error because naturally the motherboard Video card fights over Both 2080Ti GPU's over "who is going to paint pixels on your monitor?"  Google-kung-fu directed me to replace `/usr/X11/xorg.conf` with the prior one named: `xorg.conf.nvidia-xconfig-original`.  Answer is yes and no, the errors never end, but your skills get to the point where you can keep the lights on with income > expenses.

**Comment by FilippoRomeo** [comment]
```
bf16TensorCoreGemm.cu(176): error: more than one constructor applies to convert from "int" to "__nv_bfloat16":
            function "__nv_bfloat16::__nv_bfloat16(float)"
            function "__nv_bfloat16::__nv_bfloat16(double)"

bf16TensorCoreGemm.cu(182): error: more than one constructor applies to convert from "int" to "__nv_bfloat16":
            function "__nv_bfloat16::__nv_bfloat16(float)"
            function "__nv_bfloat16::__nv_bfloat16(double)"

2 errors detected in the compilation of "bf16TensorCoreGemm.cu".
Makefile:331: recipe for target 'bf16TensorCoreGemm.o' failed
make[1]: *** [bf16TensorCoreGemm.o] Error 1
make[1]: Leaving directory '/home/agx/NVIDIA_CUDA-11.0_Samples/0_Simple/bf16TensorCoreGemm'
Makefile:51: recipe for target '0_Simple/bf16TensorCoreGemm/Makefile.ph_build' failed
make: *** [0_Simple/bf16TensorCoreGemm/Makefile.ph_build] Error 2
```

same problem here

**Comment by Ru7w1k** [comment]
Arm will require an explicit cast.

Please replace
`a[i*K_GLOBAL+j] = (__nv_bfloat16)(rand() % 3);` to `a[i*K_GLOBAL+j] = (__nv_bfloat16)(float)(rand() % 3);`
and
`b[i*K_GLOBAL+j] = (__nv_bfloat16)(rand() % 3);` to `b[i*K_GLOBAL+j] = (__nv_bfloat16)(float)(rand() % 3);`

**Comment by 2yjia** [comment]
Same problem, have you solved it?

**Comment by alexvsad62** [comment]
sad@Sysadmin:~/tmp/cuda-samples/Samples/0_Introduction/asyncAPI> make TARGET_ARCH=x86_64
/usr/local/cuda/bin/nvcc -ccbin g++ -I../../../Common  -m64    --threads 0 --std=c++11 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90,code=sm_90 -gencode arch=compute_90,code=compute_90 -o asyncAPI.o -c asyncAPI.cu
g++: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.
make: *** [Makefile:328: asyncAPI.o] Ошибка 1

Which file is absent? What to do?
